version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_scanner
    ports:
      - "8000:8000"
    environment:
      VT_API_KEY: ""
    volumes:
      - .:/app
    restart: unless-stopped
